// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmnist.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMnist_CfgInitialize(XMnist *InstancePtr, XMnist_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMnist_Start(XMnist *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMnist_ReadReg(InstancePtr->Axilites_BaseAddress, XMNIST_AXILITES_ADDR_AP_CTRL) & 0x80;
    XMnist_WriteReg(InstancePtr->Axilites_BaseAddress, XMNIST_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMnist_IsDone(XMnist *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMnist_ReadReg(InstancePtr->Axilites_BaseAddress, XMNIST_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMnist_IsIdle(XMnist *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMnist_ReadReg(InstancePtr->Axilites_BaseAddress, XMNIST_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMnist_IsReady(XMnist *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMnist_ReadReg(InstancePtr->Axilites_BaseAddress, XMNIST_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMnist_EnableAutoRestart(XMnist *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMnist_WriteReg(InstancePtr->Axilites_BaseAddress, XMNIST_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XMnist_DisableAutoRestart(XMnist *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMnist_WriteReg(InstancePtr->Axilites_BaseAddress, XMNIST_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XMnist_Get_inputImage_BaseAddress(XMnist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XMNIST_AXILITES_ADDR_INPUTIMAGE_BASE);
}

u32 XMnist_Get_inputImage_HighAddress(XMnist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XMNIST_AXILITES_ADDR_INPUTIMAGE_HIGH);
}

u32 XMnist_Get_inputImage_TotalBytes(XMnist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XMNIST_AXILITES_ADDR_INPUTIMAGE_HIGH - XMNIST_AXILITES_ADDR_INPUTIMAGE_BASE + 1);
}

u32 XMnist_Get_inputImage_BitWidth(XMnist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMNIST_AXILITES_WIDTH_INPUTIMAGE;
}

u32 XMnist_Get_inputImage_Depth(XMnist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMNIST_AXILITES_DEPTH_INPUTIMAGE;
}

u32 XMnist_Write_inputImage_Words(XMnist *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XMNIST_AXILITES_ADDR_INPUTIMAGE_HIGH - XMNIST_AXILITES_ADDR_INPUTIMAGE_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XMNIST_AXILITES_ADDR_INPUTIMAGE_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XMnist_Read_inputImage_Words(XMnist *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XMNIST_AXILITES_ADDR_INPUTIMAGE_HIGH - XMNIST_AXILITES_ADDR_INPUTIMAGE_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XMNIST_AXILITES_ADDR_INPUTIMAGE_BASE + (offset + i)*4);
    }
    return length;
}

u32 XMnist_Write_inputImage_Bytes(XMnist *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XMNIST_AXILITES_ADDR_INPUTIMAGE_HIGH - XMNIST_AXILITES_ADDR_INPUTIMAGE_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XMNIST_AXILITES_ADDR_INPUTIMAGE_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XMnist_Read_inputImage_Bytes(XMnist *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XMNIST_AXILITES_ADDR_INPUTIMAGE_HIGH - XMNIST_AXILITES_ADDR_INPUTIMAGE_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XMNIST_AXILITES_ADDR_INPUTIMAGE_BASE + offset + i);
    }
    return length;
}

u32 XMnist_Get_outputVector_BaseAddress(XMnist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XMNIST_AXILITES_ADDR_OUTPUTVECTOR_BASE);
}

u32 XMnist_Get_outputVector_HighAddress(XMnist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XMNIST_AXILITES_ADDR_OUTPUTVECTOR_HIGH);
}

u32 XMnist_Get_outputVector_TotalBytes(XMnist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XMNIST_AXILITES_ADDR_OUTPUTVECTOR_HIGH - XMNIST_AXILITES_ADDR_OUTPUTVECTOR_BASE + 1);
}

u32 XMnist_Get_outputVector_BitWidth(XMnist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMNIST_AXILITES_WIDTH_OUTPUTVECTOR;
}

u32 XMnist_Get_outputVector_Depth(XMnist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMNIST_AXILITES_DEPTH_OUTPUTVECTOR;
}

u32 XMnist_Write_outputVector_Words(XMnist *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XMNIST_AXILITES_ADDR_OUTPUTVECTOR_HIGH - XMNIST_AXILITES_ADDR_OUTPUTVECTOR_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XMNIST_AXILITES_ADDR_OUTPUTVECTOR_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XMnist_Read_outputVector_Words(XMnist *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XMNIST_AXILITES_ADDR_OUTPUTVECTOR_HIGH - XMNIST_AXILITES_ADDR_OUTPUTVECTOR_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XMNIST_AXILITES_ADDR_OUTPUTVECTOR_BASE + (offset + i)*4);
    }
    return length;
}

u32 XMnist_Write_outputVector_Bytes(XMnist *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XMNIST_AXILITES_ADDR_OUTPUTVECTOR_HIGH - XMNIST_AXILITES_ADDR_OUTPUTVECTOR_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XMNIST_AXILITES_ADDR_OUTPUTVECTOR_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XMnist_Read_outputVector_Bytes(XMnist *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XMNIST_AXILITES_ADDR_OUTPUTVECTOR_HIGH - XMNIST_AXILITES_ADDR_OUTPUTVECTOR_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XMNIST_AXILITES_ADDR_OUTPUTVECTOR_BASE + offset + i);
    }
    return length;
}

void XMnist_InterruptGlobalEnable(XMnist *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMnist_WriteReg(InstancePtr->Axilites_BaseAddress, XMNIST_AXILITES_ADDR_GIE, 1);
}

void XMnist_InterruptGlobalDisable(XMnist *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMnist_WriteReg(InstancePtr->Axilites_BaseAddress, XMNIST_AXILITES_ADDR_GIE, 0);
}

void XMnist_InterruptEnable(XMnist *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMnist_ReadReg(InstancePtr->Axilites_BaseAddress, XMNIST_AXILITES_ADDR_IER);
    XMnist_WriteReg(InstancePtr->Axilites_BaseAddress, XMNIST_AXILITES_ADDR_IER, Register | Mask);
}

void XMnist_InterruptDisable(XMnist *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMnist_ReadReg(InstancePtr->Axilites_BaseAddress, XMNIST_AXILITES_ADDR_IER);
    XMnist_WriteReg(InstancePtr->Axilites_BaseAddress, XMNIST_AXILITES_ADDR_IER, Register & (~Mask));
}

void XMnist_InterruptClear(XMnist *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMnist_WriteReg(InstancePtr->Axilites_BaseAddress, XMNIST_AXILITES_ADDR_ISR, Mask);
}

u32 XMnist_InterruptGetEnabled(XMnist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMnist_ReadReg(InstancePtr->Axilites_BaseAddress, XMNIST_AXILITES_ADDR_IER);
}

u32 XMnist_InterruptGetStatus(XMnist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMnist_ReadReg(InstancePtr->Axilites_BaseAddress, XMNIST_AXILITES_ADDR_ISR);
}

