-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mnist_ip1Biases_rom is 
    generic(
             dwidth     : integer := 32; 
             awidth     : integer := 5; 
             mem_size    : integer := 30
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of mnist_ip1Biases_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 => "10111101100001001010100011110001", 
    1 => "10111100111111110011111101111001", 
    2 => "00111101100111001010110000100101", 
    3 => "10111101001011011000110011101011", 
    4 => "00111110010100101010101010000110", 
    5 => "10111101100000111100110111111000", 
    6 => "00111110010011010110011111110100", 
    7 => "10111101001101010010111111110000", 
    8 => "00111101010011111100010010111000", 
    9 => "10111101111100111100000000000101", 
    10 => "10111101101011001110110110101011", 
    11 => "00111101110101000001010101000110", 
    12 => "10111101001100110101010011110101", 
    13 => "00111101111111000010101100111000", 
    14 => "00111110000100110110010110111000", 
    15 => "10111101001000000001001110010111", 
    16 => "00111111000000000001100000000110", 
    17 => "00111110100001000101100110000000", 
    18 => "00111100001011110111000011011010", 
    19 => "10111101011001010100011001100100", 
    20 => "10111101000011010111010011111011", 
    21 => "10111101011111100111111000000000", 
    22 => "00111100101010010110110110010110", 
    23 => "10111100111000011010100111100001", 
    24 => "00111100110001100000010110011100", 
    25 => "10111101011000101100000110011010", 
    26 => "00111101001111011010111010111000", 
    27 => "10111100110001101010111110101001", 
    28 => "00111110100001101100110010100011", 
    29 => "10111101001111010101001010110010" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "select_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "distributed";

attribute EQUIVALENT_REGISTER_REMOVAL : string;
begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity mnist_ip1Biases is
    generic (
        DataWidth : INTEGER := 32;
        AddressRange : INTEGER := 30;
        AddressWidth : INTEGER := 5);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of mnist_ip1Biases is
    component mnist_ip1Biases_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    mnist_ip1Biases_rom_U :  component mnist_ip1Biases_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


