// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XMNIST_H
#define XMNIST_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmnist_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XMnist_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XMnist;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMnist_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMnist_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMnist_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMnist_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMnist_Initialize(XMnist *InstancePtr, u16 DeviceId);
XMnist_Config* XMnist_LookupConfig(u16 DeviceId);
int XMnist_CfgInitialize(XMnist *InstancePtr, XMnist_Config *ConfigPtr);
#else
int XMnist_Initialize(XMnist *InstancePtr, const char* InstanceName);
int XMnist_Release(XMnist *InstancePtr);
#endif

void XMnist_Start(XMnist *InstancePtr);
u32 XMnist_IsDone(XMnist *InstancePtr);
u32 XMnist_IsIdle(XMnist *InstancePtr);
u32 XMnist_IsReady(XMnist *InstancePtr);
void XMnist_EnableAutoRestart(XMnist *InstancePtr);
void XMnist_DisableAutoRestart(XMnist *InstancePtr);

u32 XMnist_Get_inputImage_BaseAddress(XMnist *InstancePtr);
u32 XMnist_Get_inputImage_HighAddress(XMnist *InstancePtr);
u32 XMnist_Get_inputImage_TotalBytes(XMnist *InstancePtr);
u32 XMnist_Get_inputImage_BitWidth(XMnist *InstancePtr);
u32 XMnist_Get_inputImage_Depth(XMnist *InstancePtr);
u32 XMnist_Write_inputImage_Words(XMnist *InstancePtr, int offset, int *data, int length);
u32 XMnist_Read_inputImage_Words(XMnist *InstancePtr, int offset, int *data, int length);
u32 XMnist_Write_inputImage_Bytes(XMnist *InstancePtr, int offset, char *data, int length);
u32 XMnist_Read_inputImage_Bytes(XMnist *InstancePtr, int offset, char *data, int length);
u32 XMnist_Get_outputVector_BaseAddress(XMnist *InstancePtr);
u32 XMnist_Get_outputVector_HighAddress(XMnist *InstancePtr);
u32 XMnist_Get_outputVector_TotalBytes(XMnist *InstancePtr);
u32 XMnist_Get_outputVector_BitWidth(XMnist *InstancePtr);
u32 XMnist_Get_outputVector_Depth(XMnist *InstancePtr);
u32 XMnist_Write_outputVector_Words(XMnist *InstancePtr, int offset, int *data, int length);
u32 XMnist_Read_outputVector_Words(XMnist *InstancePtr, int offset, int *data, int length);
u32 XMnist_Write_outputVector_Bytes(XMnist *InstancePtr, int offset, char *data, int length);
u32 XMnist_Read_outputVector_Bytes(XMnist *InstancePtr, int offset, char *data, int length);

void XMnist_InterruptGlobalEnable(XMnist *InstancePtr);
void XMnist_InterruptGlobalDisable(XMnist *InstancePtr);
void XMnist_InterruptEnable(XMnist *InstancePtr, u32 Mask);
void XMnist_InterruptDisable(XMnist *InstancePtr, u32 Mask);
void XMnist_InterruptClear(XMnist *InstancePtr, u32 Mask);
u32 XMnist_InterruptGetEnabled(XMnist *InstancePtr);
u32 XMnist_InterruptGetStatus(XMnist *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
